import { useEffect, useState } from 'react'
import toast from 'react-hot-toast'
import { MessageSquare, CheckCircle2, XCircle, Download, Clock3 } from 'lucide-react'
import { supabase } from '../../lib/supabaseClient'
import { useAuth } from '../../context/AuthContext'

export default function B2BInquiries(){
 const {user}=useAuth();const [items,setItems]=useState([]);const [exporting,setExporting]=useState(false);const [busy,setBusy]=useState(null)
 async function load(){const {data,error}=await supabase.from('market_inquiries').select('*,products(title,bulk_price,bulk_min_quantity)').eq('artisan_id',user.id).order('created_at',{ascending:false});if(error)toast.error(error.message);setItems(data||[])}
 useEffect(()=>{if(user)load()},[user])
 async function exportCatalog(){setExporting(true);try{const {data,error}=await supabase.from('products').select('title,description,material,dimensions,price,bulk_price,bulk_min_quantity,stock_quantity,tags,status').eq('artisan_id',user.id).eq('status','approved').eq('b2b_ready',true);if(error)throw error;const head=['title','description','material','dimensions','price','bulk_price','bulk_min_quantity','stock_quantity','tags','status'];const esc=v=>`"${String(Array.isArray(v)?v.join(' | '):v??'').replaceAll('"','""')}"`;const csv=[head.join(','),...(data||[]).map(r=>head.map(k=>esc(r[k])).join(','))].join('\n');const blob=new Blob([csv],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='craft-connect-marketplace-ready-catalog.csv';a.click();URL.revokeObjectURL(a.href);toast.success('Catalog CSV exported')}catch(e){toast.error(e.message)}finally{setExporting(false)}}
 async function decide(id,status){setBusy(id);const {error}=await supabase.from('market_inquiries').update({status}).eq('id',id).eq('artisan_id',user.id);if(error)toast.error(error.message);else{toast.success(status==='accepted'?'Bulk request accepted':'Bulk request rejected');load()}setBusy(null)}
 return <div className="max-w-5xl mx-auto px-4 py-8"><div className="mb-6"><span className="text-xs font-semibold text-craft-orange uppercase">Direct Market Linkage</span><h1 className="text-3xl font-bold mt-1">B2B Inquiries</h1><p className="text-gray-500 mt-2">You decide whether you can fulfil each buyer request. Admin does not approve individual bulk requests.</p></div><div className="card bg-orange-50/60 border-orange-100 mb-5"><div className="flex gap-3"><Clock3 className="text-craft-orange mt-0.5"/><div><p className="font-semibold">B2B rules</p><p className="text-sm text-gray-600">Every request is at least <b>40 pieces</b> and has a delivery date at least <b>6 days</b> from the request date.</p></div></div></div><button onClick={exportCatalog} disabled={exporting} className="btn-outline flex items-center gap-2 mb-5"><Download className="w-4 h-4"/>{exporting?'Preparing…':'Export marketplace-ready catalog'}</button>{items.length===0?<div className="card py-16 text-center text-gray-500"><MessageSquare className="w-10 h-10 mx-auto mb-3"/><p className="font-semibold text-gray-800">No buyer inquiries yet</p></div>:<div className="space-y-4">{items.map(x=><div className="card" key={x.id}><div className="flex flex-col lg:flex-row lg:items-start justify-between gap-4"><div className="min-w-0"><h3 className="font-semibold">{x.products?.title||'Product'}</h3><p className="text-sm text-gray-500 mt-1">{x.buyer_company} · {x.buyer_name}</p><p className="text-sm mt-2"><b>{x.quantity} pieces</b> {x.target_price?`· target ₹${x.target_price}/unit`:''} · <b>needed by {x.delivery_date}</b></p><p className="text-sm text-gray-600 mt-2">{x.message||'No message'}</p><p className="text-xs text-gray-400 mt-2">{x.buyer_email} {x.buyer_phone?`· ${x.buyer_phone}`:''}</p></div><div className="flex gap-2 flex-wrap lg:justify-end"><span className="px-2 py-1 rounded-full bg-gray-100 text-xs font-semibold h-fit">{x.status}</span>{['new','viewed'].includes(x.status)&&<><button disabled={busy===x.id} className="btn-primary text-xs flex items-center gap-1" onClick={()=>decide(x.id,'accepted')}><CheckCircle2 className="w-3 h-3"/> Accept request</button><button disabled={busy===x.id} className="btn-outline text-xs flex items-center gap-1" onClick={()=>decide(x.id,'rejected')}><XCircle className="w-3 h-3"/> Reject</button></>}{x.status==='new'&&<button className="btn-secondary text-xs" onClick={()=>decide(x.id,'viewed')}>Mark viewed</button>}</div></div></div>)}</div>}</div>}
