import { useEffect, useMemo, useState } from 'react'
import { Download, Globe2, RefreshCw, Send, ShieldCheck } from 'lucide-react'
import toast from 'react-hot-toast'
import { supabase, callEdgeFunction } from '../../lib/supabaseClient'
import { useAuth } from '../../context/AuthContext'

function download(name, content, type='application/json'){
  const blob=new Blob([content],{type}); const url=URL.createObjectURL(blob); const a=document.createElement('a'); a.href=url; a.download=name; a.click(); URL.revokeObjectURL(url)
}
function csvCell(v){ const s=Array.isArray(v)?v.join('|'):String(v??''); return `"${s.replaceAll('"','""')}"` }

export default function MarketplaceLinkage(){
  const {user}=useAuth(); const [products,setProducts]=useState([]); const [loading,setLoading]=useState(true); const [syncing,setSyncing]=useState(false); const [status,setStatus]=useState(null)
  async function load(){
    if(!user)return; setLoading(true)
    const {data,error}=await supabase.from('products').select('id,title,description,material,dimensions,production_time_days,tags,price,stock_quantity,location,product_images(storage_path,is_primary),categories(name,slug)').eq('artisan_id',user.id).eq('status','approved').gt('stock_quantity',0).order('updated_at',{ascending:false})
    if(error) toast.error(error.message); setProducts(data||[]); setLoading(false)
  }
  useEffect(()=>{load()},[user])
  const rows=useMemo(()=>products.map(p=>{const images=(p.product_images||[]).sort((a,b)=>Number(b.is_primary)-Number(a.is_primary)).map(x=>supabase.storage.from('product-images').getPublicUrl(x.storage_path).data.publicUrl); return {id:p.id,title:p.title,description:p.description||'',material:p.material||'',dimensions:p.dimensions||'',production_time_days:p.production_time_days||'',tags:p.tags||[],price:Number(p.price)||0,stock_quantity:p.stock_quantity,location:p.location||'',category:p.categories?.name||'',category_slug:p.categories?.slug||'',image_urls:images}}),[products])
  async function sync(){
    if(!rows.length)return toast.error('No approved in-stock products to sync.')
    setSyncing(true); try{const r=await callEdgeFunction('marketplace-sync',{products:rows}); setStatus(r); if(r.synced)toast.success('Marketplace connector accepted the catalog.'); else toast('Export created. Configure MARKETPLACE_SYNC_URL for live sync.',{icon:'ℹ️'})}catch(e){toast.error(e.message)}finally{setSyncing(false)}
  }
  const csv=[['id','title','description','material','dimensions','production_time_days','tags','price_inr','stock_quantity','location','category','category_slug','image_urls'].map(csvCell).join(','),...rows.map(r=>[r.id,r.title,r.description,r.material,r.dimensions,r.production_time_days,r.tags,r.price,r.stock_quantity,r.location,r.category,r.category_slug,r.image_urls].map(csvCell).join(','))].join('\n')
  return <div className="max-w-6xl mx-auto px-4 py-8"><div className="flex flex-col md:flex-row md:items-end justify-between gap-4 mb-6"><div><span className="text-xs font-semibold text-craft-orange uppercase tracking-wider">SIH 26090 · Market Linkage</span><h1 className="text-3xl font-bold mt-1">Government & B2B Marketplace Hub</h1><p className="text-gray-500 mt-2">Publish your approved catalog to a configured marketplace connector, or export a clean catalog package for GeM/ONDC/onboarding partners. No fake marketplace status is shown.</p></div><button onClick={load} className="btn-outline inline-flex items-center gap-2"><RefreshCw className="w-4 h-4"/> Refresh</button></div>
    <div className="grid lg:grid-cols-3 gap-4 mb-6"><div className="card"><Globe2 className="w-7 h-7 text-craft-orange"/><p className="font-semibold mt-2">B2B direct requests</p><p className="text-sm text-gray-500">Already live in Craft Connect: bulk buyers can request any approved product from its artisan.</p></div><div className="card"><ShieldCheck className="w-7 h-7 text-tech-teal"/><p className="font-semibold mt-2">Approved catalog only</p><p className="text-sm text-gray-500">Only approved and in-stock products are included in marketplace exports.</p></div><div className="card"><Send className="w-7 h-7 text-craft-orange"/><p className="font-semibold mt-2">Connector-ready</p><p className="text-sm text-gray-500">A secure Edge Function can POST the catalog to your government/e-commerce integration endpoint.</p></div></div>
    <div className="card mb-6"><div className="flex flex-col sm:flex-row gap-2 sm:items-center sm:justify-between"><div><p className="font-semibold">Catalog actions</p><p className="text-xs text-gray-500 mt-1">{loading?'Loading…':`${rows.length} approved in-stock product${rows.length===1?'':'s'} ready`}</p></div><div className="flex flex-wrap gap-2"><button disabled={!rows.length} onClick={()=>download('craft-connect-marketplace.json',JSON.stringify({source:'Craft Connect',format_version:'1.0',generated_at:new Date().toISOString(),products:rows},null,2))} className="btn-secondary inline-flex items-center gap-2"><Download className="w-4 h-4"/> Download JSON</button><button disabled={!rows.length} onClick={()=>download('craft-connect-marketplace.csv',csv,'text/csv;charset=utf-8')} className="btn-outline inline-flex items-center gap-2"><Download className="w-4 h-4"/> Download CSV</button><button disabled={!rows.length||syncing} onClick={sync} className="btn-primary inline-flex items-center gap-2"><Send className="w-4 h-4"/>{syncing?'Syncing…':'Sync to marketplace connector'}</button></div></div>{status&&<div className="mt-4 rounded-xl border bg-gray-50 p-3 text-sm"><b>{status.synced?'Live connector response':'Export response'}</b><p className="text-gray-600 mt-1">{status.message||'Connector completed.'}</p>{status.endpoint&&<p className="text-xs text-gray-400 mt-1">Endpoint: {status.endpoint}</p>}</div>}</div>
    <div className="card"><div className="flex items-center justify-between mb-3"><div><p className="font-semibold">Marketplace catalog preview</p><p className="text-xs text-gray-500">Images are included as public Supabase Storage URLs so a connector can ingest them.</p></div></div>{loading?<p className="text-sm text-gray-500">Loading…</p>:!rows.length?<p className="text-sm text-gray-500">No approved in-stock products found.</p>:<div className="overflow-auto"><table className="min-w-full text-sm"><thead><tr className="text-left border-b"><th className="py-2 pr-4">Product</th><th className="py-2 pr-4">Category</th><th className="py-2 pr-4">Price</th><th className="py-2 pr-4">Stock</th><th className="py-2">Images</th></tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-b last:border-0"><td className="py-3 pr-4 font-medium">{r.title}</td><td className="py-3 pr-4">{r.category||'—'}</td><td className="py-3 pr-4">₹{r.price.toLocaleString('en-IN')}</td><td className="py-3 pr-4">{r.stock_quantity}</td><td className="py-3">{r.image_urls.length}</td></tr>)}</tbody></table></div>}</div>
    <div className="mt-5 rounded-xl border border-dashed p-4 text-sm text-gray-600"><b>Live government marketplace note:</b> GeM/ONDC integrations require the seller/network credentials, onboarding and endpoint contract issued by the respective platform. This build therefore provides the real catalog export and a secure connector hook instead of pretending that an uncredentialed public API is a live government connection. Configure <code>MARKETPLACE_SYNC_URL</code> and <code>MARKETPLACE_SYNC_API_KEY</code> in Supabase Edge Function secrets when your approved integration endpoint is available.</div>
  </div>
}
